# wrangler.toml
name = "my-hono-app"
main = "src/worker.js"   # 指向 CF 入口
compatibility_date = "2026-01-13"

# 自定义运行时标识
[vars]
RUNTIME = "cloudflare"

# D1 绑定
[[d1_databases]]
binding = "MY_DATABASE"
database_name = "hono-db"
database_id = "80cd979d-a4ad-4b42-a089-4d929a0dd6ab"

[observability]
enabled = true
head_sampling_rate = 1